title: subsymbolic
author: Mia Alexiou
email: web@subsymbolic.net
description: >- # this means to ignore newlines until "baseurl:"
  Mia’s projects, ideas and ruminations. Software engineering, mobile,
  gadgets, psychology, health, fitness, running.
baseurl: ""
url: ""

# Socials
github_username:  subsymbolic
linkedin_username: subsymbolic
mastodon:
- username: subsymbolic
  instance: fosstodon.org

rss: rss

# Rendering
theme: minima
header_pages:
  - portfolio.md
  - about.md
show_excerpts: true
excerpt_separator: <!--more--> 

# Plugins
plugins:
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled: [categories, tags]
  layout: home
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
